CREATE DATABASE IF NOT EXISTS Tombolone; /*CREARE IL DATABASE*/
SHOW DATABASES;/*MOSTRARE I POSSIBILI DATABASE*/
USE Tombolone;/*USARE DATABASE*/
CREATE TABLE IF NOT EXISTS Utenti (/*CREARE ENTITÀ CON RELATIVI CAMPI*/
    mail VARCHAR(100) NOT NULL,
    usernameUtente VARCHAR(50) NOT NULL,
    PRIMARY KEY (usernameUtente, mail),/*CHIAVE PRIMARIA MULTICAMPO*/
    nome VARCHAR(50) NOT NULL,
    cognome VARCHAR(50) NOT NULL,
    dataNascita DATE NULL,
    nazionalita VARCHAR(50) NOT NULL,
    pswd VARCHAR(100) NOT NULL,
    nCrediti INT(200) NOT NULL);
DESC Utenti;/*MOSTRARE TABELLA*/
CREATE TABLE IF NOT EXISTS Partite (/*CREARE ENTITÀ CON RELATIVI CAMPI*/
    codicePartita CHAR(13) NOT NULL,
    PRIMARY KEY (codicePartita),/*CHIAVE PRIMARIA*/
    data DATE NULL,
    nRound INT(200) NOT NULL,
    nGiocatori INT(6) NOT NULL);
DESC Partite;/*MOSTRARE TABELLA*/
CREATE TABLE IF NOT EXISTS Giocare (/*CREARE ENTITÀ CON RELATIVI CAMPI*/
	flagVinto BOOLEAN NOT NULL,
	nSchedine INT(1) NOT NULL,
	usernameUtente VARCHAR(50) NOT NULL,
	codice CHAR(13) NOT NULL,
	PRIMARY KEY(usernameUtente, codice),/*CHIAVE PRIMARIA MULTICAMPO*/
	FOREIGN KEY (usernameUtente) REFERENCES Utenti (usernameUtente),/*CHIAVE ESTERNA*/
    FOREIGN KEY (codice) REFERENCES Partite (codicePartita));/*CHIAVE ESTERNA*/
DESC Giocare;/*MOSTRARE TABELLA*/
SHOW TABLES;/*MOSTRARE TUTTE LE TABELLE DEL DATABASE*/


